---
- hosts: windows2019
  tasks:
    - name: Instalar dependencias para Alfresco
      win_chocolatey:
        name:
        - postgresql11
        - ojdkbuild11
        - tomcat
        - libreoffice-still
        - activemq
        - nginx
        state: present

